### ISSUE TITLE
Inaccurate expectations

### ISSUE THREAD

**Issue by Tolsi** [bcdev-/waves_vanity#2]
Maybe show others waiting (75, 99%?) to find this addresses? Because in our office (2-3 people), no one has found the suitable address for an hour, although the expectations of 50% is targeted 3-15 minutes.

```
./wavesvanity -m ______________________________tolsi -c ______________________________xxxxx
Vanity miner settings:
CPU threads: 8
Network: Mainnet
Char mask: ______________________________tolsi
Case mask: ______________________________xxxxx

Iterations expected: 10488824
Starting workers...
Iterations: 182263770   Elapsed time: 0 d 0 h 56 m 15 s   Speed: 53994.26 keys/second   50% chance of finding: 0 d 0 h 3 m 14 s
```

**Comment by bcdev-** [comment]
I'll investigate it further. It's possible that I have some bug in probability calculation.

**Comment by bcdev-** [comment]
Indeed, I had a bug with probability calculation with _x mask.

If the requested character was impossible in Base58 [l, I and O], the probability calculation counted them as double [as if both L and l were possible, which is obviously incorrect].

The real chance of finding tolsi is 17min [more like 25min on your machine]:
```
bc@d:~/repo/waves_vanity$ ./wavesvanity -m ______________________________tolsi -c ______________________________xxxxx
Vanity miner settings:
CPU threads: 4
Network: Mainnet
Char mask: ______________________________tolsi
Case mask: ______________________________xxxxx

Iterations expected: 82361287
Starting workers...
287793  0d 0h 0m 3s  81968.95 keys/second  50% chance: 0d 0h 16m 44s  95% chance: 0d 1h 6m 59s          
```
